name: CI

on:
  push:

jobs:
  check-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version

      - name: Set up corepack
        run: |
          npm i -g corepack
          corepack enable

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      
      - name: Check code style
        run: |
          npx biome ci ./src

      - name: Run tests
        run: |
          pnpm test
