name: CI

on:
  push:

jobs:
  check-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
      - uses: './.github/actions/setup_ci'
      
      - name: Check code style
        run: |
          npx biome ci ./src

      - name: Run tests
        run: |
          pnpm test
